"""table_v4

Revision ID: 85acef510e08
Revises: 
Create Date: 2022-11-14 15:36:25.722976

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '85acef510e08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.Column('course_name', sa.String(length=30), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('course_id')
                    )

    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('institution',
                    sa.Column('school_id', sa.Integer(), nullable=False),
                    sa.Column('school_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('principal', sa.Integer(), nullable=False),
                    sa.Column('school_admin', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['school_admin'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('school_id')
                    )
    op.create_index(op.f('ix_institution_email'), 'institution', ['email'], unique=True)
    op.create_index(op.f('ix_institution_school_id'), 'institution', ['school_id'], unique=False)
    op.create_index(op.f('ix_institution_school_name'), 'institution', ['school_name'], unique=True)
    op.create_table('parents',
                    sa.Column('parent_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('parent_id')
                    )
    op.create_table('teacher',
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['teacher_id'], ['institution.school_id'], ),
                    sa.PrimaryKeyConstraint('teacher_id')
                    )
    op.create_table('classroom',
                    sa.Column('class_id', sa.Integer(), nullable=False),
                    sa.Column('class_teacher', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['class_id'], ['institution.school_id'], ),
                    sa.ForeignKeyConstraint(['class_teacher'], ['teacher.teacher_id'], ),
                    sa.PrimaryKeyConstraint('class_id')
                    )
    op.create_table('students',
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('school_id', sa.Integer(), nullable=True),
                    sa.Column('classroom', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['classroom'], ['classroom.class_id'], ),
                    sa.ForeignKeyConstraint(['school_id'], ['institution.school_id'], ),
                    sa.PrimaryKeyConstraint('student_id'),
                    sa.UniqueConstraint('classroom')
                    )
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('classroom')
    op.drop_table('teacher')
    op.drop_table('parents')
    op.drop_index(op.f('ix_institution_school_name'), table_name='institution')
    op.drop_index(op.f('ix_institution_school_id'), table_name='institution')
    op.drop_index(op.f('ix_institution_email'), table_name='institution')
    op.drop_table('institution')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('courses')
    # ### end Alembic commands ###
